export const ADDPRODUCT = 'ADDPRODUCT';
export const DELPRODUCT = 'DECREMENT';
export const EDITPRODUCT = 'EDITPRODUCT';
export const INITIALIZEPRODUCT = 'INITIALIZEPRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';